#!/usr/bin/env bash
#
# Render a fixed-format markdown summary of the changes between two
# data/models.json snapshots. Used as the body of the weekly upstream PR.
#
# Usage: catalog-diff.sh OLD.json NEW.json
set -euo pipefail

old="$1"
new="$2"

jq -rn --slurpfile olddoc "$old" --slurpfile newdoc "$new" '
  $olddoc[0] as $old | $newdoc[0] as $new |

  def n2s: if . == null then "n/a" else tostring end;
  def price: if . == null then "n/a" else "$\(.)/M" end;
  # A missing key and an explicit null mean the same thing in the catalog;
  # strip nulls so snapshots generated by different script versions compare equal.
  def norm: with_entries(select(.value != null));
  def describe:
    "`\(.id)` (\(.name), context \(.context | n2s)" +
    (if (.input_price != null) or (.output_price != null)
     then ", in \(.input_price | price), out \(.output_price | price)"
     else "" end)
    + ")";
  def field_diffs($a; $b):
    ([($a | keys), ($b | keys)] | add | unique - ["id"])
    | map(select($a[.] != $b[.]) | "\(.) \($a[.] | n2s) → \($b[.] | n2s)")
    | join(", ");

  ([($old | keys), ($new | keys)] | add | unique) as $providers
  | [ $providers[] as $p
      | (INDEX(($old[$p] // [])[] | norm; .id)) as $o
      | (INDEX(($new[$p] // [])[] | norm; .id)) as $n
      | {
          provider: $p,
          before: ($o | length),
          after: ($n | length),
          added:   [ $n | to_entries[] | select($o[.key] == null) | .value ],
          removed: [ $o | to_entries[] | select($n[.key] == null) | .value ],
          changed: [ $o | to_entries[]
                     | select($n[.key] != null and $n[.key] != .value)
                     | {id: .key, diff: field_diffs(.value; $n[.key])} ]
        }
    ] as $rows

  | "Automated refresh of `data/models.json` from https://models.dev/api.json via `scripts/gen-models-catalog.sh`.",
    "",
    "## Summary",
    "",
    "| Provider | Models | Added | Removed | Changed |",
    "|---|---|---|---|---|",
    ($rows[] | "| \(.provider) | \(.before) → \(.after) | \(.added | length) | \(.removed | length) | \(.changed | length) |"),
    "",
    ( $rows[]
      | select((.added | length) + (.removed | length) + (.changed | length) > 0)
      | "### \(.provider)",
        "",
        (if (.added | length) > 0
         then "**Added**", (.added[] | "- \(describe)"), "" else empty end),
        (if (.removed | length) > 0
         then "**Removed**", (.removed[] | "- \(describe)"), "" else empty end),
        (if (.changed | length) > 0
         then "**Changed**", (.changed[] | "- `\(.id)`: \(.diff)"), "" else empty end)
    ),
    "Review the diff for unexpected additions or removals before merging."
'
